---
title: "Coronavirus Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(plotly)
library(lubridate)
library(corrplot)
library(scales)

#IMPORTANT! The following two lines are REQUIRED for first use of coronavirus package or data will be outdated.
#install.packages('devtools')
#devtools::install_github('RamiKrispin/coronavirus') # Type '1' into console when prompted.
library(coronavirus)
```

```{r}
# DATA FOR VISUALISATION
# Create dataframe containing world coronavirus data
global_coronavirus <-  coronavirus %>%
  group_by(type, date) %>%
  summarise(total = sum(cases, na.rm = TRUE), .groups = 'keep') %>%
  pivot_wider(names_from = type, values_from = total) %>%
  arrange(date)
```

Visualisation {data-icon='fa-globe'}
=============================

Row {data-width=150}
---
### Total Cases
```{r}
global_total_cases <- sum(global_coronavirus$confirmed)

valueBox(value = format(global_total_cases, big.mark = ','),
         icon = 'fa-line-chart',
         caption = 'Total Cases', 
         color = '#227093')
```

### Total Active
```{r}
global_total_active <- sum((global_coronavirus$confirmed - global_coronavirus$recovered - global_coronavirus$death))

valueBox(value = paste(format(global_total_active, big.mark = ','), ' (',
    round(global_total_active / global_total_cases * 100, 1),
    '%)', sep = ''),
         icon = 'fa-hospital-o',
         caption = 'Total Active', 
         color = '#218c74')
```

### Total Deaths
```{r}
global_total_deaths <- sum(global_coronavirus$death)

valueBox(value = paste(format(global_total_deaths, big.mark = ','), ' (',
    round(global_total_deaths / global_total_cases * 100, 1),
    '%)', sep = ''),
         icon = 'fa-user-md',
         caption = 'Total Deaths', 
         color = '#b33939')
```

Row 2 {.tabset}
---

### Total Cases
```{r}
global_cumulative_cases <- cumsum(global_coronavirus$confirmed)

global_cumcases_timeseries <- global_coronavirus %>%
  ggplot(aes(x = date, y = global_cumulative_cases))+
  geom_line(color = '#227093') +
  ggtitle('Total confirmed number of COVID-19 cases') +
  ylab('Cases') + 
  xlab('Date') +
  scale_y_continuous(trans = 'log10',
                     label = comma) +
  scale_x_date(date_labels = '%b %Y', 
               breaks = pretty_breaks(6)) +
  theme_light()

global_cumcases_timeseries <- ggplotly(global_cumcases_timeseries)

global_cumcases_timeseries
```

### Daily Cases
```{r}
global_totcases_timeseries <- global_coronavirus %>%
  ggplot(aes(x = date,
             y = confirmed)) +
  geom_area(fill = '#227093', alpha=0.3) +
  geom_line(color = '#227093') +
  ggtitle('Daily confirmed number of COVID-19 cases') +
  ylab('Cases') +
  xlab('Date') +
  scale_y_continuous(label = comma) +
  theme_light() +
  annotate(geom = 'text', 
           x = as.Date('2020-12-10'),
           y = 1520000,
           label = 'Reporting error',
           size = 3)

global_totcases_timeseries <- ggplotly(global_totcases_timeseries)

global_totcases_timeseries
```

### Total Deaths
```{r}
global_cumulative_deaths <- cumsum(global_coronavirus$death)

global_cumdeaths_timeseries <- global_coronavirus %>%
  ggplot(aes(x = date, y = global_cumulative_deaths))+
  geom_line(color = '#b33939') +
  ggtitle('Total confirmed number of COVID-19-related deaths') +
  ylab('Deaths') + 
  xlab('Date') +
  scale_y_continuous(trans = 'log10',
                     label = comma) +
  scale_x_date(date_labels = '%b %Y', 
               breaks = pretty_breaks(6)) +
  theme_light()

global_cumdeaths_timeseries <- ggplotly(global_cumdeaths_timeseries)

global_cumdeaths_timeseries
```

### Daily Deaths
```{r}
global_totdeaths_timeseries <- global_coronavirus %>%
  ggplot(aes(x = date,
             y = death)) +
  geom_area(fill = '#b33939', alpha=0.3) +
  geom_line(color = '#b33939') +
  ggtitle('Daily confirmed number of COVID-19-related deaths') +
  ylab('Deaths') +
  xlab('Date') +
  scale_y_continuous(label = comma) +
  theme_light()

global_totdeaths_timeseries <- ggplotly(global_totdeaths_timeseries)

global_totdeaths_timeseries
```